//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by VPC.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDR_MENU1                       101
#define IDR_POPUP_MENU                  101
#define IDC_EDIT                        101
#define IDD_VALUE_DLG                   102
#define IDC_MESSAGE                     102
#define IDC_CUR_NOMAL                   103
#define IDC_CUR_NORMAL                  103
#define ID_CON_MONO                     32771
#define ID_WND_JUST                     32773
#define ID_CON_EDGES                    32774
#define ID_CON_ADLIGHT                  32775
#define ID_CON_CNOISE                   32777
#define ID_DRAW_FREE                    32779
#define ID_DRAW_GETC                    32780
#define ID_WND_MAX                      32781
#define ID_CON_UNDO                     32782
#define ID_CON_EDGES2                   32783
#define ID_CON_NEGAP                    32784
#define ID_CON_BINARY                   32786
#define ID_CON_BESMART                  32787
#define ID_CON_MOSAIC                   32788
#define ID_DRAW_CLIP                    32789
#define ID_DRAW_NOCLIP                  32790
#define ID_CON_SOFT                     32791
#define ID_CON_PREWITT                  32792
#define ID_CON_SOBEL                    32793
#define ID_FILE_SAVEAS                  32794
#define ID_DRAW_SELECTC                 32795
#define ID_CON_ROTATE                   32796
#define ID_CON_ZOOM                     32797
#define ID_CON_ADCENTER                 32798
#define ID_FILE_DATAOUT                 32799
#define ID_FILE_CLEAR                   32800
#define ID_FILE_COPY                    32801
#define ID_FILE_PASTE                   32802
#define ID_WND_CRATIO                   32803
#define ID_CON_SSCALE                   32804
#define ID_CON_ADHEIGHT                 32806
#define ID_DRAW_LINE                    32807
#define ID_DRAW_FRECT                   32808
#define ID_CON_CDCOLOR                  32809

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         103
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
